config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # user
  # get 'user/index'
  # delete 'user/destroy/:id', to: 'user#destroy', as: 'user_destroy'

  # dashboard
  get 'dashboards', to: 'dashboard#index'
  get 'settings', to: 'setting#index'
  post 'settings/token', to: 'setting#generate_token', as: 'generate_token'
  delete 'settings/token', to: 'setting#clear_token', as: 'clear_token'

  # root: temporary
  root to: redirect('users/sign_in')

  # Devise
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # base router
  resources :routers
  resources :organizations

  # set wildcard router
  get '*organization/*path', to: 'mocks#serve_mock'
  post '*organization/*path', to: 'mocks#serve_mock'
  put '*organization/*path', to: 'mocks#serve_mock'
  patch '*organization/*path', to: 'mocks#serve_mock'
  delete '*organization/*path', to: 'mocks#serve_mock'
end

app/models/router.rb
# frozen_string_literal: true

class Router < ApplicationRecord
  belongs_to :organization

  REQUEST_METHOD = %w[GET POST PUT PATCH DELETE].freeze
  public_constant :REQUEST_METHOD
end

app/controllers/routers_controller.rb
# frozen_string_literal: true

class RoutersController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
  before_action :set_router, only: %i[show edit update destroy]

  # GET /routers or /routers.json
  def index
    @routers = Router.all
  end

  # GET /routers/1 or /routers/1.json
  def show
  end

  # GET /routers/new
  def new
    @router = Router.new
  end

  # GET /routers/1/edit
  def edit
  end

  # POST /routers or /routers.json
  def create
    @router = Router.new(router_params)

    respond_to do |format|
      if @router.save
        format.html { redirect_to router_url(@router), notice: 'Router was successfully created.' }
        format.json { render :show, status: :created, location: @router }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @router.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routers/1 or /routers/1.json
  def update
    respond_to do |format|
      if @router.update(router_params)
        format.html { redirect_to router_url(@router), notice: 'Router was successfully updated.' }
        format.json { render :show, status: :ok, location: @router }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @router.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routers/1 or /routers/1.json
  def destroy
    @router.destroy

    respond_to do |format|
      format.html { redirect_to routers_url, notice: 'Router was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_router
    @router = Router.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def router_params
    params.require(:router)['organization_id'] = current_user.organization_id
    params.require(:router).permit(:organization_id, :path, :request_method)
  end
end

app/helpers/routers_helper.rb
# frozen_string_literal: true

module RoutersHelper
end

app/views/routers/_form.html.erb
<%= form_with(model: router, class: "contents") do |form| %>
  <% if router.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(router.errors.count, "error") %> prohibited this router from being saved:</h2>

      <ul>
        <% router.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :path %>
    <%= form.text_field :path, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :request_method %>
    <%= form.text_field :request_method, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/routers/_router.html.erb
<div id="<%= dom_id router %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Organization:</strong>
    <%= router.organization_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Path:</strong>
    <%= router.path %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Request method:</strong>
    <%= router.request_method %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this router", router, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this router', edit_router_path(router), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/routers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing router</h1>

  <%= render "form", router: @router %>

  <%= link_to "Show this router", @router, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to routers", routers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/routers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Routers</h1>
    <%= link_to 'New router', new_router_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="routers" class="min-w-full">
    <%= render @routers %>
  </div>
</div>

app/views/routers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New router</h1>

  <%= render "form", router: @router %>

  <%= link_to 'Back to routers', routers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/routers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @router %>

    <%= link_to 'Edit this router', edit_router_path(@router), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this router', router_path(@router), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to routers', routers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>