config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # user
  # get 'user/index'
  # delete 'user/destroy/:id', to: 'user#destroy', as: 'user_destroy'

  # dashboard
  get 'dashboards', to: 'dashboard#index'
  get 'settings', to: 'setting#index'
  post 'settings/token', to: 'setting#generate_token', as: 'generate_token'
  delete 'settings/token', to: 'setting#clear_token', as: 'clear_token'

  # root: temporary
  root to: redirect('users/sign_in')

  # Devise
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # base router
  resources :routers
  resources :organizations

  # set wildcard router
  get '*organization/*path', to: 'mocks#serve_mock'
  post '*organization/*path', to: 'mocks#serve_mock'
  put '*organization/*path', to: 'mocks#serve_mock'
  patch '*organization/*path', to: 'mocks#serve_mock'
  delete '*organization/*path', to: 'mocks#serve_mock'
end

app/controllers/setting_controller.rb
# frozen_string_literal: true

class SettingController < ApplicationController
  layout 'dashboard'
  def index
    @settings = Settings::UseCases::UserGetToken.new(organization_id: current_user.organization_id).call
  end

  def generate_token
    result = Settings::UseCases::UserGenerateToken.new(organization_id: current_user.organization_id).call
    handle_result(settings_url, result)
  end

  def clear_token
    result = Settings::UseCases::UserClearToken.new(organization_id: current_user.organization_id).call
    handle_result(settings_url, result)
  end
end

app/views/setting/index.html.erb
<h2 class="text-lg font-medium text-gray-800 dark:text-white">Settings</h2>

<p class="mt-1 text-md text-gray-500 dark:text-gray-300">You can set everything here 👌</p>


<div class="flex flex-col mt-6">
  <div class="max-w px-8 py-4 bg-white rounded-lg shadow-md dark:bg-gray-800">
    <div class="flex items-center justify-between">
      <span class="text-sm font-light text-gray-600 dark:text-gray-400"></span>
      <% if @settings.token.nil? %>
        <%= button_to 'Generate Token', generate_token_path, method: :post, class: "rounded-lg py-2 px-5 bg-blue-600 text-white block font-medium" %>
      <% end %>
    </div>

    <div class="mt-2">
      <a href="#" class="text-xl font-bold text-gray-700 dark:text-white hover:text-gray-600 dark:hover:text-gray-200 hover:underline" tabindex="0" role="link">Access
        Token</a>
      <% if @settings.token.nil? %>
        <%== render partial: 'layouts/shared/empty_section', locals: { domain: 'Token' } %>
      <% else %>
        <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700 mt-6">
          <thead class="bg-gray-50 dark:bg-gray-800 sticky top-0">
          <tr>
            <th scope="col" class="py-3.5 px-4 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">
              <span>Token</span>
            </th>

            <th scope="col" class="relative py-3.5 px-4">
              <span class="sr-only">Actions</span>
            </th>
          </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700 dark:bg-gray-900">
          <tr>
            <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
              <div>
                <h2 class="font-medium text-gray-800 dark:text-white "><%= @settings.token %></h2>
              </div>
            </td>
            <td class="px-4 py-4 text-sm whitespace-nowrap">
              <div class="flex items-center gap-x-6">
                <%= button_to clear_token_path, method: :delete, data: { confirm: 'Are you sure you want to clear?' }, class: "text-gray-500 transition-colors duration-200 dark:hover:text-yellow-500 dark:text-gray-300 hover:text-yellow-500 focus:outline-none" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"/>
                  </svg>
                <% end %>
              </div>
            </td>
          </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>